version: 1

formatters:
  simple:
    format: '[%(levelname)-10s | %(filename)-15s | %(asctime)s] %(message)s'

handlers:
  debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "./logs/debug.log"
  error:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "./logs/errors.log"

loggers:
  debug:
    level: DEBUG
    handlers: [debug]
    propagate: false
  error:
    level: DEBUG
    handlers: [error]
    propagate: false