# name: role_id
#   name should be case-insensitive and can be a partial match for a series or group
#   role_id should be numerical -- if multiple roles, use list syntax
#     eg For the series "Ore no Genjitsu wa Ren'ai Game?? ka to Omottara Inochigake no Game datta"...
#        genj wa game: [123456, 696969]

# if "all" is used for a series name, the corresponding role will appear in every update

all: 798403122195333130
leviatan: 798403007682838590
sushi: 798403095377346610
mangadex: 798754612089192489
ann: 799105777766760469
lht: 799145507825778729
skscans: 799145542881116180