# https://leovoel.github.io/embed-visualizer/
series_update_embed: |-
  <%
    is_int= UPDATE.chap - int(UPDATE.chap) == 0
    chap_num= int(UPDATE.chap) if is_int else UPDATE.chap
  %>

  <%
    TITLE_CHAR_LIM= 999
    DESC_CHAR_LIM= 150

    def truncate(x, limit, trail="..."):
      x= str(x).replace('"', r'\"')
      if len(x) > limit+len(trail):
        return x[:limit] + trail
      return x

    desc= truncate(UPDATE.desc, DESC_CHAR_LIM)
    desc= desc.replace("\n", "\n  ")
    desc= desc if desc else "N/A"

    title= truncate(UPDATE.title, TITLE_CHAR_LIM)
    title= title.replace("\n"," ")
    title= f"{title} - "
    if UPDATE.vol > -1:
      title+= f"Volume {UPDATE.vol}, "
    title+= f"Chapter {chap_num}"
  %>

  title: "${UPDATE.title}"
  url: "${UPDATE.link}"
  description: |-
    ${desc}
  % if UPDATE.cover_link:
  image:
    url: "${UPDATE.cover_link}"
  % endif
  fields:
    - name: group
      value: "[${UPDATE.group_name}](${UPDATE.group_link})"
      inline: True
    - name: series page
      value: "[link](${UPDATE.series_link})"
      inline: True

  content: |-
    ${title}
    ${UPDATE.link}